/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Person_Profile.Profile;

/**
 *
 * @author shubhangisrivastava
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    Profile profile;
    
    public DisplayJPanel(Profile profile) {
        initComponents();
        
        this.profile=profile;
        displayProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeographicData = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblTelNum = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        lblEmailAddr = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMedicalRecNum = new javax.swing.JLabel();
        lblHealthPlanBenefitNum = new javax.swing.JLabel();
        lblBankAcNum = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        lblVehicleIdentifier = new javax.swing.JLabel();
        lblDeviceIdentifier = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblIPAddr = new javax.swing.JLabel();
        lblFingerPrnt = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblUniqueID = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txttelnum = new javax.swing.JTextField();
        txtFaxNum = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMedicalRecNum = new javax.swing.JTextField();
        txtHealthBenNum = new javax.swing.JTextField();
        txtLicenseNum = new javax.swing.JTextField();
        txtVehicleIdent = new javax.swing.JTextField();
        txtDeviceIdent = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtIPAddr = new javax.swing.JTextField();
        txtFingerPrint = new javax.swing.JTextField();
        txtImg = new javax.swing.JTextField();
        txtUniqueID = new javax.swing.JTextField();
        txtBankAccNum = new javax.swing.JFormattedTextField();

        LblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitle.setText("VIEW PERSON DETAILS");

        lblName.setText("Name :");

        lblGeographicData.setText("City :");

        lblDOB.setText("Date Of Birth :");

        lblTelNum.setText("Telephone Number :");

        lblFaxNum.setText("Email Address :");

        lblEmailAddr.setText("Fax Number :");

        lblSSN.setText("SSN :");

        lblMedicalRecNum.setText("Medical Record Number :");

        lblHealthPlanBenefitNum.setText("Health Plan Benefit Number :");

        lblBankAcNum.setText("Bank Account Number :");

        lblLicenseNum.setText("License Number :");

        lblVehicleIdentifier.setText("Vehicle Identifier :");

        lblDeviceIdentifier.setText("Device Identifier :");

        lblLinkedIn.setText("LinkedIn Profile :");

        lblIPAddr.setText("IP Address :");

        lblFingerPrnt.setText("FingerPrint :");

        lblImage.setText("Image :");

        lblUniqueID.setText("Unique ID :");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        txttelnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelnumActionPerformed(evt);
            }
        });

        txtFaxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumActionPerformed(evt);
            }
        });

        txtBankAccNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblGeographicData)
                    .addComponent(lblEmailAddr)
                    .addComponent(lblSSN)
                    .addComponent(lblMedicalRecNum)
                    .addComponent(lblBankAcNum)
                    .addComponent(lblLicenseNum)
                    .addComponent(lblVehicleIdentifier)
                    .addComponent(lblDeviceIdentifier)
                    .addComponent(lblLinkedIn)
                    .addComponent(lblIPAddr)
                    .addComponent(lblFingerPrnt)
                    .addComponent(lblImage)
                    .addComponent(lblUniqueID)
                    .addComponent(lblTelNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFaxNum)
                    .addComponent(lblHealthPlanBenefitNum))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHealthBenNum)
                    .addComponent(txtName)
                    .addComponent(txtCity)
                    .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(txttelnum, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(txtFaxNum)
                    .addComponent(txtEmail)
                    .addComponent(txtSSN)
                    .addComponent(txtMedicalRecNum)
                    .addComponent(txtLicenseNum)
                    .addComponent(txtVehicleIdent)
                    .addComponent(txtDeviceIdent)
                    .addComponent(txtLinkedIn)
                    .addComponent(txtIPAddr)
                    .addComponent(txtFingerPrint)
                    .addComponent(txtImg)
                    .addComponent(txtUniqueID)
                    .addComponent(txtBankAccNum))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addComponent(LblTitle)
                                                                                        .addGap(21, 21, 21)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                            .addComponent(lblName)
                                                                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGap(6, 6, 6)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                            .addComponent(lblGeographicData)
                                                                                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGap(6, 6, 6)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(lblDOB))
                                                                                        .addGap(6, 6, 6)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                            .addComponent(txttelnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                            .addComponent(lblTelNum))
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                            .addComponent(lblEmailAddr)
                                                                                            .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                            .addComponent(lblFaxNum)
                                                                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(lblSSN))
                                                                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(lblMedicalRecNum))
                                                                            .addComponent(txtMedicalRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(lblHealthPlanBenefitNum)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(lblBankAcNum)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(lblLicenseNum))
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(txtHealthBenNum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtBankAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(lblVehicleIdentifier))
                                                            .addComponent(txtVehicleIdent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lblDeviceIdentifier))
                                                    .addComponent(txtDeviceIdent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblLinkedIn))
                                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblIPAddr))
                                    .addComponent(txtIPAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFingerPrnt))
                            .addComponent(txtFingerPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImage))
                    .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniqueID)
                    .addComponent(txtUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txttelnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelnumActionPerformed

    private void txtFaxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumActionPerformed

    private void txtBankAccNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBankAcNum;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceIdentifier;
    private javax.swing.JLabel lblEmailAddr;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblFingerPrnt;
    private javax.swing.JLabel lblGeographicData;
    private javax.swing.JLabel lblHealthPlanBenefitNum;
    private javax.swing.JLabel lblIPAddr;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalRecNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelNum;
    private javax.swing.JLabel lblUniqueID;
    private javax.swing.JLabel lblVehicleIdentifier;
    private javax.swing.JFormattedTextField txtBankAccNum;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDeviceIdent;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtFingerPrint;
    private javax.swing.JTextField txtHealthBenNum;
    private javax.swing.JTextField txtIPAddr;
    private javax.swing.JTextField txtImg;
    private javax.swing.JTextField txtLicenseNum;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalRecNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtUniqueID;
    private javax.swing.JTextField txtVehicleIdent;
    private javax.swing.JTextField txttelnum;
    // End of variables declaration//GEN-END:variables

    private void displayProfile() {
        txtName.setText(profile.getName());
        txtCity.setText(profile.getCity());
        txttelnum.setText(profile.getTelephone());
        txtFaxNum.setText(profile.getFax_num());
        txtEmail.setText(profile.getEmail_addr());
        txtSSN.setText(profile.getSsn());
        txtMedicalRecNum.setText(profile.getMedicaid_rec_num());
        txtHealthBenNum.setText(profile.getHealth_plan_ben_num());
        txtBankAccNum.setText(Long.toString(profile.getBank_acc_num()));
        txtLicenseNum.setText(profile.getLicense_num());
        txtVehicleIdent.setText(profile.getVehicle_identifier());
        txtDeviceIdent.setText(profile.getDevice_identifier());
        txtLinkedIn.setText(profile.getLinkedIn());
        txtIPAddr.setText(profile.getIPAddr());
        txtFingerPrint.setText(profile.getBio_identity());
        txtImg.setText(profile.getPhoto());
        txtUniqueID.setText(profile.getUnique_Identifier());
    }
}
